### ISSUE TITLE
Trouble with capturing 5Ghz on Raspberry P 3B+

### ISSUE THREAD

**Issue by michlevltech** [seemoo-lab/nexmon_csi#1]
Hi!
First, I wanted to say that this is a wonderful project!

I'm trying to capture data using my Raspberry Pi 3B+ (bcm43455c0).
I've manage to configure it to capture CSI on the 2.4GHz band without any issue, but when I was trying to capture date on the 5GHz band with a 80Mhz signal bandwidth I was unsuccessful. I tried to provide a different set chanspecs in the configuration and none of them seemed to work. (I validated the channel parameters using a spectrum analyzer).

Is there any way I can investigate this?
I'm running on monitor mode. Channel is 48, 80MHz bandwidth.

Thank you!

**Comment by jlinktu** [comment]
Hi,
I can not reproduce the described behavior. Capturing on channel 48 with 80MHz bandwidth works perfectly fine on the Raspberry Pi 3B+ I am using. The chanspec should be 0xe32a. You can verify the correct channel was set by looking at the output of running _nexutil -k_. Also make sure your filters are all set up correctly!
