### ISSUE TITLE
CSI phase inversion and Jumping

### ISSUE THREAD

**Issue by YaohuaLee** [seemoo-lab/nexmon_csi#100]
Hello，I encountered two problems when I used as86u to collect CSI .

1: As long as the incident angle of the signal is greater than a certain angle (estimated at about 35 degrees), there is a sign reversal problem (sign changes to negative sign) during the AOA estimation. I'm sure there's nothing wrong with my algorithm
![image](https://user-images.githubusercontent.com/15908826/86738919-0f0f1580-c068-11ea-8dd3-2628e430b511.png)

2: The phase of the collected four antennas will jump suddenly, which seriously affects my positioning accuracy, but I can't solve it.
![image](https://user-images.githubusercontent.com/15908826/86739710-aa07ef80-c068-11ea-8d21-f073f16b0c3f.png)

I tried a lot, but  couldn't solve the problem, I guess there's something wrong with the receiver itself.
I hope someone can give me some advice. Thank you very much.

**Comment by yangtat** [comment]
Hello, I have the same problem as you. Have you solved it finally?

**Comment by Deltaaaaaaaaaa** [comment]
@leeyewhwa Hello, Have you solved the phase jumping problem? Could you please give some clue?

**Comment by yujianyuanhaha** [comment]
@leeyewhwa @yangtat I also meet the problem, I will treat these less appeared as outliers.

Meanwhile, did you  have the plot that  phase different between different antennas, are they nearly constant over subcarriers?

Best

Jet

**Comment by yangtat** [comment]
@yujianyuanhaha The phase different between different antennas are nearly constant.
![fig1](https://user-images.githubusercontent.com/46256632/127831958-93e6d480-9223-4d65-9d6e-852b2b54bcf1.png)

**Comment by yujianyuanhaha** [comment]
@yangtat thanks, looks pretty good with down to 5-degree variations. Does this plot come after RF-chain calibration? Is the phase different offset constant the same for all subcarriers？

**Comment by yangtat** [comment]
@yujianyuanhaha I just used the raw data collected by Nexmon. `phase_diff=angle(csi_11./csi_12)` csi_11 and csi_12 are the CSI matrix of the two receiving antennas.
I think the phase difference offset constant of different subcarriers is the same, but it seems to be different when the time between two acquisition is longer.

**Comment by yujianyuanhaha** [comment]
@yangtat thanks
my results are like
![image](https://user-images.githubusercontent.com/9403813/127948864-fe2b632e-4d2b-4035-9bfc-950e60d4d132.png)

**Comment by yangtat** [comment]
@yujianyuanhaha I agree with your conclusion.
My previous plot is phase difference of one subcarrier over about 800 packets.
![untitled](https://user-images.githubusercontent.com/46256632/127950741-fbc9bcf3-815f-4e0d-994d-b36735a80668.jpg)
There seems to be  offset between the subcarriers in my image.
The device I use is a Nexus 6P

**Comment by yujianyuanhaha** [comment]
@yangtat  thanks for sharing.

interesting, I also found the pattern in some antennas pair changes over time (altho previous plot 1th-5th does not)
![image](https://user-images.githubusercontent.com/9403813/128015992-4925dce7-f8f8-4f54-983c-6622cee40c36.png)
This plot is phase difference over time for 3rd and 11th spatial steams, with 15 consective packages, the first 6 packages (in red) follow one pattern, while remain switch to another pattern.

**Comment by yujianyuanhaha** [comment]
@leeyewhwa well, it looks to me the sudden jump is about 0.5 (from you plot is -0.15 to 0.35), it match the (**On 2.4 GHz bands, it appears that each antenna experiences an unknown phase shift by a multiple of π/2 (or 90 degrees)**.)[https://github.com/dhalperi/linux-80211n-csitool-supplementary/issues/6#issuecomment-77093589].

So you can switch to 5G to try again.
