### ISSUE TITLE
Problem about generating traffic

### ISSUE THREAD

**Issue by huhanwj** [seemoo-lab/nexmon_csi#104]
I successfully installed the tool on Raspberry Pi 4B but got a bit confused about the traffic generation. 
Should I try to generate traffic between my PC and the RPi or just traffic between my PC and my laptop/router on the specified channel?

**Comment by zeroby0** [comment]
Send pings to your router IP via any wireless device connected to it the router. That should generate wireless traffic, and the CSI for packets in that traffic will be calculated by the RPi.

Also check out the pull request #46 if you're using Rpi and are experiencing problems with csi collection freezing.

**Comment by huhanwj** [comment]
> 
> 
> Send pings to your router IP via any wireless device connected to the router. That should generate wireless traffic. The Rpi will calculate CSI for packets in that traffic.
> 
> Also check out the pull request #46 if you're using Rpi and are experiencing problems with csi collection freezing.

Thanks for your help!
