### ISSUE TITLE
Can't not find wlan0 on raspberry pi 4 B after installing the firmware.

### ISSUE THREAD

**Issue by YogiWu** [seemoo-lab/nexmon_csi#106]
I have followed the tips in the README.But after I can't not find wlan0 on raspberry pi 4 B after installing the firmware.When I run `ifconfig`,there's on wlan0 and `ifconfig wlan0 up` will got the error `wlan0: ERROR while getting interface flags: No such device`.My system kernal is `Linux raspberrypi 5.4.51-v7l+ #1326 SMP Fri Jul 17 10:51:18 BST 2020 armv7l GNU/Linux`.Is it the key of the problem that I should get the 4.19?

**Comment by jlinktu** [comment]
Added support for kernel 5.4 https://github.com/seemoo-lab/nexmon_csi/commit/34e6075c335e295248e0209d6dca38096230c3c1
