### ISSUE TITLE
RFC: Releases

### ISSUE THREAD

**Issue by zeroby0** [seemoo-lab/nexmon_csi#120]
# Motivation

Nexmon_CSI is in active development and undergoes changes that make it temporarily unstable on some combinations of Hardware and Operating System. Users spend a substantial time figuring out the installation bugs as a result. This is evident from the 16 issues solely about setting up Nexmon_CSI on a single device type.

If we provide the users with a known good configuration, installation will be much easier and reliable. 

# Design

A ReadMe.md file which describes a deterministic way to install Nexmon_CSI on a particular device is called a Release. Scripts to automate the installation maybe included with this file.

Releases are titled semantically to reflect their targeted hardware and software. For Raspbarry Pi, this would be `device-os-kernel` (pi3Bplus-buster-4.19.97).

Each Release and it's accompanying scripts are placed in a folder named same as the Release's Title. All release folders are placed in a folder called `releases`.

# Creating a new Release

1. Fork the nexmon_csi repository.
2. Create a branch called `release-<Release Title>`.
3. Add a new folder to the `releases` folder named `<Release Title>`.
4. Add a Readme.md file to it to describe your release and installation process.
5. Add any additional scripts you may need. Change main Readme to include your release.
6. Commit and create a Pull Request from your release branch to Nexmon_CSI master.

The Pull Request should be titled `Release <Release Title>`. See #122 for example.

Note that installing a release on a new device should *always* produce the same result. New commits may be added to this repository, so you should [use `git checkout` to ensure the same version of the software is run](https://github.com/seemoo-lab/nexmon_csi/pull/122/commits/1b7b4e75125aa72e9d088be2065594928b884321#diff-64f1a38d69bd85c61fdad96ebd4e708bR44-R48).

# Updating Readme

This refers to the [main Readme.md file](https://github.com/seemoo-lab/nexmon_csi/blob/master/README.md) at the root of Nexmon_CSI repository.

You should update this file in your commit to let users know about the release. The best way to do this is different for each device. Here is what I think would be suitable for Raspberry Pi.

[README.md#bcm43455c0](https://github.com/seemoo-lab/nexmon_csi/blob/master/README.md#bcm43455c0)
# bcm43455c0

Click the release that is suitable with your setup and follow it's instructions. Generic installation instructions are given below.

|Raspberry Pi|Operating System|Kernel Version|Release|
|---|---|---|---|
|Raspberry Pi 3B+| Buster Lite 2020-02-13 | v4.19.97|[pi3Bplus-buster-4.19.97](https://github.com/seemoo-lab/nexmon_csi/pull/122)|
|Raspberry Pi 4B| Buster Lite 2020-02-13 | v4.19.97|[pi4B-buster-4.19.97](https://github.com/seemoo-lab/nexmon_csi/pull/122)|

On your Raspberry Pi 3B+/4 running Raspbian/Raspberry Pi OS with kernel 4.19 or 5.4 run the following:

1. Make sure the following commands are executed as root: sudo su

Note: The release links to the Pull Request here, but it should actually link to your Release Readme file.

I think releases would be much time saving for users. If I had them, I would have completed my thesis a month earlier. Please add your comments and suggestions on how releases could be better implemented. Thank you.

**Comment by matthiasseemoo** [comment]
Hi zeroby0,
thank you for your release strategy suggestion.
However, I would not want to add an additional directory for releases. First of all, Both RPi3 and 4 have exactly the same Wi-Fi chip. And if you are running the same OS release, the CSI extractor shall work the same. Additionally, we generally keep multiple versions of patched drivers. So that even older OS releases can be used with the latest state of the repository.

For handling versions, we (at least intend to) use git tags. Those tags will also end up in the built firmware (see https://github.com/seemoo-lab/nexmon_csi/blob/master/src/version.c). Then, you always know exactly on which repository state a firmware was built. However, I have to admit, that lately we did not really use tags anymore.

@jlinktu: I think we should start adding tags to working states of our releases. Preferably using a versioning scheme such as https://semver.org/. Before tagging a state of the repo, we shall execute regression tests on all supported platforms so that we always ensure that each release works as expected.

**Comment by zeroby0** [comment]
Hi Mathias!

Sorry for the delayed response. Well labelled git tags would be equally good! Could you enable Wiki as well? There's hordes of valuable info in the issues, but it's not well organized.

**Comment by matthiasseemoo** [comment]
Done ;-)

**Comment by zeroby0** [comment]
Awesome! It looks like wiki editing is restricted to collaborators only, please [change it to public](https://docs.github.com/en/free-pro-team@latest/github/building-a-strong-community/changing-access-permissions-for-wikis) so all of us can contribute. Thanks :)

**Comment by matthiasseemoo** [comment]
I do not want to open the wiki for public editing as it makes it harder to review and approve changes. You could clone the wiki locally and send us your proposed changes as a patch.

**Comment by zeroby0** [comment]
I didn't know that was possible. I'll do that. Thank you.
