### ISSUE TITLE
Can i get csi from two antennas of  Nexus 6P at the same time?

### ISSUE THREAD

**Issue by yangtat** [seemoo-lab/nexmon_csi#136]
The Nexus 6P has two antennas. Can i get csi from two antennas of  Nexus 6P at the same time?

**Comment by jlinktu** [comment]
Yes.

**Comment by yangtat** [comment]
> Yes.

Thank you very much for your reply!
If I want to collect CSI using two antennas on the Nexus 6P and one antenna on the AP, how do I modify makecsiparams-C and -N?

**Comment by jlinktu** [comment]
`-C3` as `3 = b0011` to extract for core/antenna 0 and 1
and
`-N1` as `1 = b0001` to extract for spatial stream 0.
For each received WiFi frame that matches your filter settings you should then get two UDPs holding CSI, one for each core.
