### ISSUE TITLE
How write the captured CSI into .pcap file?

### ISSUE THREAD

**Issue by Colin-Guolin** [seemoo-lab/nexmon_csi#140]
Hi guys

I am new to linux. I have install the nexmon on my Raspberry 4 follow the instruction, and the packets can be captured by using commend 'tcpdump -i wlan0 dst port 5500'.

There is a Matlab code in '/utils/MATLAB' allows me to read the example CSI from 'example.pcap' file, but I am still struggling how to create and write my own CSI value into a new '.pcap' after I used commend 'tcpdump -i wlan0 dst port 5500', so that I can use machine learning algorithm to process it on my laptop, anyone could give me some instruction?

**Comment by zeroby0** [comment]
`tcpdump -i wlan0 dst port 5500 -vv -w output.pcap -c 1000`

The -w flag [optional] sets the file to which tcpdump writes packets
The -vv flag [optional] tells tcpdump to print statistics on the terminal
The -c flag [optional] is how many packets tcpdump will write before exiting

You can use man pages to find usage information about virtually any tool in Linux. For example, `man tcpdump` or `tcpdump --help`. Also, Google is your friend :)
