### ISSUE TITLE
Is it necessary to build on Xubuntu 16.04 LTS?, got error on Ubuntu 20.04

### ISSUE THREAD

**Issue by Mcalvinlee** [seemoo-lab/nexmon_csi#156]
greetings:
I'm using  Nexus6p ,because my laptop's hardware doesn't support Xubuntu 16.04 LTS, I had to compile the source code on Ubuntu 20.04. But I got an error at step 12.
 COLLECTING STATISTICS read /home/lmc/projectCSI/nexmon/nexmon/STATISTICS.md for more information
  COMPILING src/version.c => obj/version.o (details: log/compiler.log)
  ASSEMBLING UCODE src/csi.ucode.bcm4358.7_112_300_14_sta.asm => gen/ucode.bin
make: *** [Makefile:219：gen/ucode.bin] Error 1
Is it necessary to build on Xubuntu 16.04 LTS?

**Comment by jlinktu** [comment]
Works on 20.04 too. Make sure you follow the README.
You probably either forgot to `source setup_env.sh` or to run `make` in the nexmon root directory once.

**Comment by zeroby0** [comment]
Have you installed g++?
https://github.com/seemoo-lab/nexmon_csi/issues/28
