### ISSUE TITLE
Long recording

### ISSUE THREAD

**Issue by yael1994** [seemoo-lab/nexmon_csi#190]
I want to recording for 24 hours the csi data. 
I build a script that save every 100 packets in file and in a loop start a new recording. 
after about 7 or a little bit more the I got 0 packets.
what I can do?

the script:

#!/bin/bash

function scan_wifi() {
	local bandwidth=$1
	local channel=$2
	cd /home/pi/nexmon/patches/bcm43455c0/7_45_189/nexmon_csi/utils/makecsiparams

	local chanSpec=$(./makecsiparams -C 1 -N 1 -c "$channel/$bandwidth" -m b8:27:eb:c2:34:9e)

	ifconfig wlan0 up

	nexutil -Iwlan0 -s500 -b -l34 -v$chanSpec

	# setting up monitor fails when it already exists. Can be happily ignored.
	iw phy `iw dev wlan0 info | gawk '/wiphy/ {printf "phy" $2}'` interface add mon0 type monitor
	ifconfig mon0 up
}

scan_wifi 40 36
cd /home/pi/
while true
do
	time_now=$(date +%d_%m_%Y__%H_%S_%m) 
	tcpdump -i wlan0 dst port 5500 -c 100 -w "./scan2/file$time_now.pcap" & sleep 15;
	size_file=$(stat -c %s  "/home/pi/scan2/file$time_now.pcap")
	if [ "$size_file" -eq "0" ];
	then
		echo $size_file
                rm "/home/pi/scan2/file$time_now.pcap"
	fi
done

the results:
![printscreen](https://user-images.githubusercontent.com/45081145/109413334-7db53080-79b5-11eb-8862-0b2a7b1bff70.png)

**Comment by zeroby0** [comment]
Heyo!

I don't know why the packets collected are 0, maybe the amsdu fixes in pull request https://github.com/seemoo-lab/nexmon_csi/pull/46 will fix it. I have a fork with the fixes applied: https://github.com/nexmonster/nexmon_csi/tree/pi-5.4.51 (don't run apt upgrade if you use it).

Tcpdump has a feature inbuilt to split pcap files. The -C flag, from the `man tcpdump` page:

>        -C file_size
>               Before  writing a raw packet to a savefile, check whether the file is
>               currently larger than file_size and, if so, close the  current  save‐
>               file  and  open  a  new one.  Savefiles after the first savefile will
>               have the name specified with the -w flag, with  a  number  after  it,
>               starting at 1 and continuing upward.  The units of file_size are mil‐
>               lions of bytes (1,000,000 bytes, not 1,048,576 bytes).

You can calculate how many bytes a 100 sample file will have and use it to split.
