### ISSUE TITLE
Chip Goes Down After A While - Chanspec Output Seems Wrong

### ISSUE THREAD

**Issue by Adam-Antios** [seemoo-lab/nexmon_csi#198]
I built and installed the Nexmon CSI tool in a Raspberry Pi Model 3 B+ with RPi OS using kernel 5.4.83-v7+.

I check that the chanspec is correctly set and the command `nexutil -m` produces a 2, but after a minute or so the chip goes down as the chanspec produces the code `0x6863 85/160` and the `nexutil -m` gives a 0. This happens whether I run` tcpdump` and gather packets, or do absolutely nothing. 

Moreover, at any time if I try to set the channel and the bandwidth as 1/20 instead of getting as a result an output 1/20 I get 1 which seems wrong. I thought that this might have been a formatting issue and thus I tried setting it as 01/20 or 001/20, with no different results. In order to use this channel and bandwidth I changed the `src/regulations.c: additional_valid_chanspecs[]` first.

**Comment by Asafe33** [comment]
were you able to find a solution?

**Comment by Adam-Antios** [comment]
Unfortunately no, I am sorry.

**Comment by Asafe33** [comment]
so which way did you go? How did you capture the csi data?

**Comment by Adam-Antios** [comment]
I didn't. I abandoned the effort due to the experimental nature of the project. It wasn't mature enough for my purposes.
