### ISSUE TITLE
"Recipe for target 'gen/ucode.bin' failed on Asus RT-AC86U router installation error

### ISSUE THREAD

**Issue by GerbenGheysens** [seemoo-lab/nexmon_csi#202]
<img width="840" alt="image" src="https://user-images.githubusercontent.com/80955648/114532322-0679ea00-9c4d-11eb-8216-23b71acff172.png">
When I want to install the firmware on the Asus RT-AC86U router I've got an error message about the gen/ucode.bin target. 
Does anyone know how to solve this issue?

**Comment by zeroby0** [comment]
Did you source the setup file before building?

I also have pre-compiled binaries here that you can use: https://github.com/nexmonster/nexmon_csi/discussions/2

**Comment by GerbenGheysens** [comment]
Yes, setup was done properly, but I will try with the pre-compiled binaries :) thx!

**Comment by zeroby0** [comment]
There should be compiler logs somewhere nearby in the directory structure, they might contain a more verbose error message.

The pre-compiled binaries will reduce the work you need to do, but if you need to build it for some reason, I have the build guide here: https://github.com/nexmonster/nexmon_csi/discussions/7.
