### ISSUE TITLE
Extracting CSI without MAC Address

### ISSUE THREAD

**Issue by Junye97** [seemoo-lab/nexmon_csi#21]
Hi there, 

It seems that nexmon_csi requires the MAC address of the devices in order to get the CSI. Is there a way to get around that and extract CSI without any MAC address required, i.e. extracting all the CSI packets from a specific channel? I am digging into the source code but haven't made much progress. 

Cheers

**Comment by jlinktu** [comment]
Hi,
https://github.com/seemoo-lab/nexmon_csi/blob/8260f5b7a8617ed064f561b972b66c535ed49329/src/ioctl.c#L133
just set the number of mac addresses to filter for to 0.

**Comment by Junye97** [comment]
Hi jlinktu, 

Thank you for your reply. However, if I set the `params->n_mac_addr = 0;` as follows:

![image](https://user-images.githubusercontent.com/18410289/73229108-bd1ab780-41cc-11ea-8751-c44bbcafe24e.png)

there will be no CSI packet captured. Please advise. 

Cheers

**Comment by zeroby0** [comment]
There is another attribute above "use_pkt_filter", try setting that to 0. I'm about to test in 1 hr, will let you know if that works.

**Comment by jlinktu** [comment]
There is an error in the ucode code preventing csi extraction when no mac address is given. I try to push a fix for that soon.

**Comment by Junye97** [comment]
Thank you very much @jlinktu.

**Comment by zeroby0** [comment]
@jlinktu  Please do, I need it for my thesis. Thanks :D

**Comment by jlinktu** [comment]
Done.
If _n_mac_addr_ is set to 0, address filtering is disabled.
If you use `makecsiparams` to configure the extractor you can set this by simply leaving out the _-m_ parameter.

Using this for the bcm43455c0 and bcm4358 also requires updating your main nexmon repository!

**Comment by Junye97** [comment]
Hi @jlinktu, thank you so much for your effort. It works for me now and I'm closing this issue. 

Cheers
