### ISSUE TITLE
WIFI 5G SSID missing after install firmware

### ISSUE THREAD

**Issue by zlin-ir** [seemoo-lab/nexmon_csi#24]
Hi guys,

I am using Raspberry PI 4 Model B.
Not sure if this issue has happened to you as well that, after running make install-firmware to compile the nexmon_csi firmware patch, my RPI can no longer find any WIFI 5G SSID, which was connected before running this step. I have re-installed the whole system but this problem happened again.

Anyone knows the reason why this happening?

Thanks

**Comment by SniperssSs** [comment]
Same here. So I cannot set the wifi channel same to the csi collected one i.e. 157 [cry]

**Comment by SniperssSs** [comment]
But actually, I have lost all the wireless connections after `pkill wpa_supplicant` in the usage

**Comment by zlin-ir** [comment]
@SniperssSs You can find some WIFI SSID via iw wlan0 scan except for those 5Gs.

**Comment by zeroby0** [comment]
If you ran `apt-get remove wpasupplicant`, that removes wpasupplicant and aps dont show up. Instead, use `iw wlan0 scan`.

**Comment by zlin-ir** [comment]
@zeroby0 I have successfully managed to listen to the WIFI info via tcpdump. But it stopped working after a while (about 20 minutes). And I use `iw wlan0 scan` again, it outputs _connection timed out_. Did you have this issue?

**Comment by SniperssSs** [comment]
> @zeroby0 I have successfully managed to listen to the WIFI info via tcpdump. But it stopped working after a while (about 20 minutes). And I use `iw wlan0 scan` again, it outputs _connection timed out_. Did you have this issue?

Could you please share how you solved the previous problems?

**Comment by zlin-ir** [comment]
> > @zeroby0 I have successfully managed to listen to the WIFI info via tcpdump. But it stopped working after a while (about 20 minutes). And I use `iw wlan0 scan` again, it outputs _connection timed out_. Did you have this issue?
> 
> Could you please share how you solved the previous problems?

I used RPI 3B+ instead, problem solved😂

**Comment by zlin-ir** [comment]
> > @zeroby0 I have successfully managed to listen to the WIFI info via tcpdump. But it stopped working after a while (about 20 minutes). And I use `iw wlan0 scan` again, it outputs _connection timed out_. Did you have this issue?
> 
> Could you please share how you solved the previous problems?

Also, you need to change the router's channel and bandwidth on the router's control panel, say channel 157 and bandwidth 80MHZ

**Comment by SniperssSs** [comment]
Thanks a lot. ( Lol @zlin-ir
