### ISSUE TITLE
Can not capture CSI data on spatial streams No.3 and No.4

### ISSUE THREAD

**Issue by wolke1526** [seemoo-lab/nexmon_csi#250]
Greetings,
I have successfully collected CSI on an ASUS RT-ac86u router. However, when I configure the spatial stream number as 4 by using the `makecsiparams`, there is no CSI data captured on spatial streams No.3 and No.4 as shown in the figure. 
Here are the parameters I used when collecting data on 5G band  `mcp -c 36/80 -C 0xf -N 0xf -m <Tx_mac_address> -b 0x88`, 

Data is collected on chan 36 with 4 x 4 setup
![1](https://user-images.githubusercontent.com/83703158/135795579-59b9f978-5bae-42a4-9916-9a67670ec447.png)

But when I try to collect CSI data on the 2.4GHz band, it works just fine. Data of all antenna is collected except Rx No.3 which is the internal antenna and only goes 5G signal, referring to #199. 
Data is collected on chan 10 with 4 x 4 setup
![2](https://user-images.githubusercontent.com/83703158/135796614-b03c84a5-cef7-4578-8701-c228e3e6d460.png)

Currently, I'm using another router (also ac86u) as a transmitter and a smartphone as a receiver to create the communication link (literally using the phone to play video on youtube), the Monitor router is placed nearby the phone and overhearing the link. 
I've tried changing the Chan to 108, the data can be captured but nothing different, and when I changing the Chan to like 120, 124, 128, I cannot even capture any data.
Here are my questions:
1. With my setup, why the CSI data can not be collected on spatial streams No.3 and No.4?
2. Is there anything I should change/notice when I try to collect data on high channels like 120, 124, or 128 (can only be set to 128 on ac86u)?
Any suggestion/advice will be really appreciated!

**Comment by t5670116** [comment]
> With my setup, why the CSI data can not be collected on spatial streams No.3 and No.4?
I am facing the same problem.
How did you solve it?
I would love to know.
