### ISSUE TITLE
Nexutil problem on Raspberry Pi4

### ISSUE THREAD

**Issue by Zilliax-Barry** [seemoo-lab/nexmon_csi#264]
Hi!
I'm using RaspberryPi 4.
When I run 'nexutil -Iwlan0 -s500 -b -l34 -v$str', it gave me an error.

I tried every related method in the issues but all of them failed. I don't know it is my problem or not, but please let me know how to fix this.
Besides, is there any other solution that I can use? Because I hope I don't need to change the Raspberry Pi version.

I get this same error:
nex_init_netlink: socket error (93: Protocol not supported)
nex_init_netlink: socket error (93: Protocol not supported)
nex_init_netlink: bind error (9: Bad file descriptor)
nex_init_netlink: connect error (9: Bad file descriptor)
ERR (__nex_driver_netlink): no valid answer received

**Comment by Asafe33** [comment]
were you able to find a solution?
