### ISSUE TITLE
The length of UDP packets is wrong

### ISSUE THREAD

**Issue by xcl0416** [seemoo-lab/nexmon_csi#27]
Sorry to bother you. I have followed the instruction and log the UDP packets with Nexus 5 like this.  
![image](https://user-images.githubusercontent.com/14949508/71613390-2e247a80-2be1-11ea-8b2d-c3a5c7bcb5cf.png)
However, when I process the pcap file with MATLAB program, I cannot find CSI from it. I find that the length of UDP packet of my pcap file is different from yours, which is 1034. I have no idea about this. Could you please tell me why.

**Comment by jlinktu** [comment]
Adapt https://github.com/seemoo-lab/nexmon_csi/blob/8260f5b7a8617ed064f561b972b66c535ed49329/utils/matlab/csireader.m#L13 to 20, the bandwidth in MHz you used during extraction. You also want to change https://github.com/seemoo-lab/nexmon_csi/blob/8260f5b7a8617ed064f561b972b66c535ed49329/utils/matlab/csireader.m#L12 to _bcm4339_ for processing captures made with a Nexus 5.

**Comment by xcl0416** [comment]
It works, thank you!
