### ISSUE TITLE
Rt-AC86U extracts CSI amplitude and phase

### ISSUE THREAD

**Issue by QUANAAAA** [seemoo-lab/nexmon_csi#274]
Hello, I try to use ASUS RT-AC86U 80M to extract the amplitude and phase of CSI. The centimeter connects the output stream of the transmitter to the receiver. I find that the phase difference between antenna channels is not stable with time, and its shape is similar to rectangular wave. I don't think it is caused by CFO, SFO, PDD, etc. Some people know what causes this, and is there a solution?
Thank you
![anglediff2](https://user-images.githubusercontent.com/105221800/182083035-641cd8f3-b867-437c-8f45-16b1f4c08dd8.png)
![jzabs2](https://user-images.githubusercontent.com/105221800/182083053-8dfdfa7e-d0c9-47ca-b03d-08a90eb9981b.png)

**Comment by Huxiiiao** [comment]
Hello, how do you extract CSI?

**Comment by QUANAAAA** [comment]
I am not sure if you are asking me how to get CSI with RTAC86U router, or about the CSI amplitude and phase difference obtained in the above case.

**Comment by Huxiiiao** [comment]
I used the UbiLocate tool to obtain the CSI, but I am not sure if the CSI obtained is correct, so I ask which method or tool you used to obtain the CSI from RT-AC86U




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "seemoo-lab/nexmon_csi"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年11月28日(星期二) 中午1:19
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [seemoo-lab/nexmon_csi] Rt-AC86U extracts CSI amplitude and phase (Issue #274)





 
I am not sure if you are asking me how to get CSI with RTAC86U router, or about the CSI amplitude and phase difference obtained in the above case.

**Comment by QUANAAAA** [comment]
I don't know about UbiLocate tool. We use the nexmon firmware, which is available in the Nexmon code section. We followed the steps on the website to collect CSI.




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2023年11月28日(星期二) 下午2:26
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [seemoo-lab/nexmon_csi] Rt-AC86U extracts CSI amplitude and phase (Issue #274)





 I used the UbiLocate tool to obtain the CSI, but I am not sure if the CSI obtained is correct, so I ask which method or tool you used to obtain the CSI from RT-AC86U 
 
 
 
 
 ------------------&amp;nbsp;原始邮件&amp;nbsp;------------------ 
 发件人:                                                                                                                        "seemoo-lab/nexmon_csi"                                                                                    ***@***.***&amp;gt;; 
 发送时间:&amp;nbsp;2023年11月28日(星期二) 中午1:19 
 ***@***.***&amp;gt;; 
 ***@***.******@***.***&amp;gt;; 
 主题:&amp;nbsp;Re: [seemoo-lab/nexmon_csi] Rt-AC86U extracts CSI amplitude and phase (Issue #274) 
 
 
 
 
 
   
 I am not sure if you are asking me how to get CSI with RTAC86U router, or about the CSI amplitude and phase difference obtained in the above case.

**Comment by Huxiiiao** [comment]
OK，thank you very much



---Original---
From: ***@***.***&gt;
Date: Tue, Nov 28, 2023 14:37 PM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [seemoo-lab/nexmon_csi] Rt-AC86U extracts CSI amplitude and phase(Issue #274)




 I don't know about UbiLocate tool. We use the nexmon firmware, which is available in the Nexmon code section. We followed the steps on the website to collect CSI. 
 
 
 
 
 ------------------&amp;nbsp;原始邮件&amp;nbsp;------------------ 
 发件人: ***@***.***&amp;gt;;  
 发送时间: 2023年11月28日(星期二) 下午2:26 
 收件人: ***@***.***&amp;gt;;  
 抄送: ***@***.***&amp;gt;; ***@***.***&amp;gt;;  
 主题: Re: [seemoo-lab/nexmon_csi] Rt-AC86U extracts CSI amplitude and phase (Issue #274) 
 
 
 
 
 
  I used the UbiLocate tool to obtain the CSI, but I am not sure if the CSI obtained is correct, so I ask which method or tool you used to obtain the CSI from RT-AC86U  
   
   
   
   
  ------------------&amp;amp;nbsp;原始邮件&amp;amp;nbsp;------------------  
  发件人:                                                                                                                        "seemoo-lab/nexmon_csi"                                                                                    ***@***.***&amp;amp;gt;;  
  发送时间:&amp;amp;nbsp;2023年11月28日(星期二) 中午1:19  
  ***@***.***&amp;amp;gt;;  
  ***@***.******@***.***&amp;amp;gt;;  
  主题:&amp;amp;nbsp;Re: [seemoo-lab/nexmon_csi] Rt-AC86U extracts CSI amplitude and phase (Issue #274)  
   
   
   
   
   
     
  I am not sure if you are asking me how to get CSI with RTAC86U router, or about the CSI amplitude and phase difference obtained in the above case.

**Comment by sie2** [comment]
You can potentially try our tool [nexmon_csi_gui](https://github.com/ConnectedSystemsLab/nexmon_csi_gui/tree/main) which we used to debug issues with RT-AC86U in real-time.

**Comment by Huxiiiao** [comment]
OK，thank you very much



---Original---
From: "Emerson ***@***.***&gt;
Date: Tue, Dec 19, 2023 15:48 PM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [seemoo-lab/nexmon_csi] Rt-AC86U extracts CSI amplitude and phase(Issue #274)




 
You can potentially try our tool nexmon_csi_gui which we used to debug issues with RT-AC86U in real-time.
