### ISSUE TITLE
Frame Injection from ASUS RT-AC86U (bcm4366c0)

### ISSUE THREAD

**Issue by Davide-Zamboni** [seemoo-lab/nexmon_csi#287]
I am trying for days to implement frame injection on ASUS RT-AC86U (bcm4366c0) without any success.  I want simply to use two routers, one to send a custom payload on a specific bandwidth and the other will do the CSI extraction.

I read this: [https://github.com/seemoo-lab/nexmon_csi/issues/166](166). It seems someone has already accomplished this but the code isn't public. Furthermore, as stated here: [https://github.com/seemoo-lab/nexmon_csi/issues/16](16), it simply may consist in the implementation of the sendframe.c file for the bcm4366c0, but it requires reverse engineering the firmware.

Any Help?

@zeroby0

**Comment by zeroby0** [comment]
I think I remember reading @Gi-z implemented frame injection a while ago, but it was unstable.  And I don't remember if it was for rt-ac86u, it might've been for pi. As far as I understand, sendframe.c has not been implemented for bcm4366c0: https://github.com/seemoo-lab/nexmon/tree/master/patches/bcm4366c0/10_10_122_20

You **might** be able to install something like aircrack-ng on merlin-wrt and inject packets there, but I don't know much about it. I recommend asking in https://github.com/seemoo-lab/nexmon/issues though - code for injection lives in that repository.

**Comment by jlinktu** [comment]
Due to the frequent request I will add a frame transmission/injection example patch for the `bcm4366c0` to the [nexmon](https://github.com/seemoo-lab/nexmon) repository in the next few days.

**Comment by jlinktu** [comment]
Here you go:
https://github.com/seemoo-lab/nexmon_tx_task

**Comment by Davide-Zamboni** [comment]
Thanks a lot @jlinktu 🎉
