### ISSUE TITLE
how can i solve this problem? (empty part of data)

### ISSUE THREAD

**Issue by rack570** [seemoo-lab/nexmon_csi#297]
Hello, I'm new to nexmon extractor. I was able to extract the pcap file correctly according to the instructions. But I have a few questions. I tried to visualize the data using Gi-z's CSIKit, but there is a part in the middle where there is no data (white part). How can I solve this phenomenon? And there's one more thing. Visualizing the data extracts the same 2000 packets, each of which has a different part about time on the x-axis. Is there a way to time each extraction data?

channel 6 bandwidth 20MHz (there is no last data)
![Figure 2023-05-28 210636](https://github.com/seemoo-lab/nexmon_csi/assets/131440518/bf734269-ae9a-4435-bdda-f3afb0588c16)

channel 44 bandwidth 80MHz (data is empty between.)
![ch44bw80](https://github.com/seemoo-lab/nexmon_csi/assets/131440518/97f1e566-7962-4af8-8d53-fbf8c313e0cb)

Is the emptying of this data not a problem with nexmon extractor, but does csikit need to be modified? here is the code
----------------------------------------------------
from CSIKit.filters.passband import lowpass
from CSIKit.filters.statistical import running_mean
from CSIKit.util.filters import hampel

from CSIKit.reader import get_reader
from CSIKit.tools.batch_graph import BatchGraph
from CSIKit.util import csitools

import numpy as np

my_reader = get_reader("path pcap file")
csi_data = my_reader.read_file("path pcap file", scaled=True)
csi_matrix, no_frames, no_subcarriers = csitools.get_CSI(csi_data, metric="amplitude")

csi_matrix_first = csi_matrix[:, :, 0, 0]
csi_matrix_squeezed = np.squeeze(csi_matrix_first)

for x in range(no_frames):
  csi_matrix_squeezed[x] = lowpass(csi_matrix_squeezed[x], 10, 100, 5)
  csi_matrix_squeezed[x] = hampel(csi_matrix_squeezed[x], 10, 3)
  csi_matrix_squeezed[x] = running_mean(csi_matrix_squeezed[x], 10)

BatchGraph.plot_heatmap(csi_matrix_squeezed, csi_data.timestamps)

**Comment by Gi-z** [comment]
This is not an issue with Nexmon, but with CSIKit. Please close this and remake your issue in the CSIKit repo.
