### ISSUE TITLE
Collect and process the CSI datagrams on-the-fly

### ISSUE THREAD

**Issue by sarielkk** [seemoo-lab/nexmon_csi#310]
You mentioned in the paper “Free Your CSI: A Channel State Information Extraction Platform For Modern Wi-Fi Chipsets”, can the method of collecting and processing CSI in real time only be based on the fact that both the transceiver and the transceiver are nexus mobile phones?
Tx is router, Rx is nexus5, can the method also be available?

**Comment by jlinktu** [comment]
Sure, as long as the transmitted frames are receivable by the Nexus 5 it doesn't matter what kind of device the transmitter of these frames is.
