### ISSUE TITLE
How to understand nextmon firmware code

### ISSUE THREAD

**Issue by yjxb1** [seemoo-lab/nexmon_csi#311]
Can everyone help me answer my questions？
1.I am using system version 5.10, so I am using brcmfmac_5.10. What are the various uses of the files in this folder for the nextmon firmware of y-nextmon? How can beginners understand the entire firmware code or become familiar with the entire process.
2.Which file is the code for sending UDP data in?

![QRP$@N G(F5%MS1{NQRLD72](https://github.com/seemoo-lab/nexmon_csi/assets/140472878/64bbde7d-8e5e-433e-af8a-ba29747af9f4)

**Comment by zeroby0** [comment]
I found the free your csi paper very helpful in understanding the code. It's linked in the readme.

**Comment by yjxb1** [comment]
> I found the free your csi paper very helpful in understanding the code. It's linked in the readme.

thanks.

**Comment by jlinktu** [comment]
`brcmfmac_5.10.y-nexmon` is a slightly modified version of the `brcmfmac` driver from the raspberrypi linux sources version `5.10.y` https://github.com/raspberrypi/linux/tree/rpi-5.10.y
If you want to understand the modifications, try starting with a diff between the nexmon version and https://github.com/raspberrypi/linux/tree/rpi-5.10.y/drivers/net/wireless/broadcom/brcm80211/brcmfmac
But be aware that this is only the driver side running on the host and not part of the firmware.

**Comment by yjxb1** [comment]
> `brcmfmac_5.10.y-nexmon` is a slightly modified version of the driver from the raspberrypi linux sources version https://github.com/raspberrypi/linux/tree/rpi-5.10.y If you want to understand the modifications, try starting with a diff between the nexmon version and https://github.com/raspberrypi/linux/tree/rpi-5.10.y/drivers/net/wireless/broadcom/brcm80211/brcmfmac But be aware that this is only the driver side running on the host and not part of the firmware.`brcmfmac``5.10.y`

I am in the csi of the src folder_ I found the xmit() function for sending UDP packets in the extractor file, but I would like to know the content of this function. Where can I find it?
![4T({)I5S$~)O6BIYVCIUPUS](https://github.com/seemoo-lab/nexmon_csi/assets/140472878/7d391e03-4899-41a1-a32d-c6a039912071)
![L T`_V_7B%}@{$Y }{FQH9O](https://github.com/seemoo-lab/nexmon_csi/assets/140472878/047785d8-9720-47a0-9d37-5ad407ff19e8)

**Comment by jlinktu** [comment]
This repository does not contain the code behind the function that is assigned to `wl->dev->chained->funcs->xmit`. It is part of the original firmware which is distributed as binary blob. You could analyze the function by disassembling the firmware and/or generating pseudo-code of it with a reversing tool of your choice, e.g. Ghidra.

**Comment by yjxb1** [comment]
> This repository does not contain the code behind the function that is assigned to . It is part of the original firmware which is distributed as binary blob. You could analyze the function by disassembling the firmware and/or generating pseudo-code of it with a reversing tool of your choice, e.g. Ghidra.`wl->dev->chained->funcs->xmit`



Thank you for your answer。
