### ISSUE TITLE
Howto disable monitor mode in NEXUS 6P

### ISSUE THREAD

**Issue by bingwl** [seemoo-lab/nexmon_csi#326]
After implement `nexutil -Iwlan0 -m1`, I can successfully capture the CSI of the WiFi packets. However, I cannot normally connect to any WiFi hotsopt. After I implement `nexutil -p1`, the smartphone can scan the surrounding hotspot, but still cannot connect to them. I wonder how should I do to recover the smartphone to normal mode.

**Comment by jlinktu** [comment]
You can install the original firmware that can be found here: https://github.com/seemoo-lab/nexmon/blob/master/firmwares/bcm4358/7_112_300_14_sta/fw_bcmdhd.bin
