### ISSUE TITLE
How to configure two Asus routers

### ISSUE THREAD

**Issue by sarielkk** [seemoo-lab/nexmon_csi#327]
Hello author, thank you for your work.
I want to use two Asus AC86U routers to collect CSI. My idea is for one router to be connected to the network as Tx, and the other router to be configured as Rx according to this project. The two are set up in the same frequency band and channel, and connected to the computer through a LAN port using a network cable at Rx. May I ask if my understanding is correct?

When I use the command "nexutil -Iwlan0 -s500 -b -l34 -vm+IBEQGIAgAAESIzRFWqu6q7qrsAAAAAAAAAAAAAAAAAAA==",  I got "nexutil: cannot find command". Do you know what the reason is？

![1111](https://github.com/seemoo-lab/nexmon_csi/assets/52898164/f8412f30-7249-4bb7-a7f0-8c50fe5a761d)

**Comment by jlinktu** [comment]
If you followed the README then `nexutil` is placed at `/jffs/nexutil`. And if you did not put that location to your `PATH` environment variable you have to provide the location to call it: `/jffs/nexutil ...`

**Comment by jlinktu** [comment]
However, the example command you provided will not work as there is no interface called `wlan0` on the Asus RT-AC86U. The interfaces are called `eth5` for 2.4 GHz and `eth6` for 5Ghz.
Edit: Just saw that you correctly used `eth6` in the command in the screenshot.

**Comment by sarielkk** [comment]
> If you followed the README then `nexutil` is placed at `/jffs/nexutil`. And if you did not put that location to your `PATH` environment variable you have to provide the location to call it: `/jffs/nexutil ...`

Thank you for your reply. When I use `/jffs/nexutil ...` , I can run it successfully. 
I have another question. I want to use two ASUS routers to capture CSI, should I configure Tx according to [nexmon_tx_task](https://github.com/seemoo-lab/nexmon_tx_task) , and configure Rx according to [nexmon_csi](https://github.com/seemoo-lab/nexmon_csi) ?

**Comment by sarielkk** [comment]
Additionally, I am using one router as Tx and the other ASUS router based on Nexmon_CSI as RX. I connected the LAN port of RX to my laptop using a network cable, and ping tx with `ping 192.168.1.1 -i 0.1` , but I was unable to receive CSI data. Am I missing any steps?

Should I use PC1 to connect Tx and PC2 to connect Rx for capture CSI？

![333](https://github.com/seemoo-lab/nexmon_csi/assets/52898164/eea5f931-f72b-40dc-9a39-209e4a85c90c)

**Comment by jlinktu** [comment]
> > If you followed the README then `nexutil` is placed at `/jffs/nexutil`. And if you did not put that location to your `PATH` environment variable you have to provide the location to call it: `/jffs/nexutil ...`
> 
> Thank you for your reply. When I use `/jffs/nexutil ...` , I can run it successfully. 
> I have another question. I want to use two ASUS routers to capture CSI, should I configure Tx according to [nexmon_tx_task](https://github.com/seemoo-lab/nexmon_tx_task) , and configure Rx according to [nexmon_csi](https://github.com/seemoo-lab/nexmon_csi) ?

Yes, that is one of many possible setups.

**Comment by jlinktu** [comment]
> Additionally, I am using one router as Tx and the other ASUS router based on Nexmon_CSI as RX. I connected the LAN port of RX to my laptop using a network cable, and ping tx with `ping 192.168.1.1 -i 0.1` , but I was unable to receive CSI data. Am I missing any steps?
> 
> Should I use PC1 to connect Tx and PC2 to connect Rx for capture CSI？
> 
> ![333](https://github.com/seemoo-lab/nexmon_csi/assets/52898164/eea5f931-f72b-40dc-9a39-209e4a85c90c)
> 
> 
> 

If you use `nexmon_tx_task` there is no need to `ping`.

Also I advise against using `ping` as a traffic generator in general. If you do not want to inject frames with `nexmon_tx_task` but generate traffic on tcpip level I suggest using `iperf`.


Not capturing any CSI UDPs can have many reasons, usually this is due to misconfiguration. Also check out the FAQ.

**Comment by sarielkk** [comment]
> > Additionally, I am using one router as Tx and the other ASUS router based on Nexmon_CSI as RX. I connected the LAN port of RX to my laptop using a network cable, and ping tx with `ping 192.168.1.1 -i 0.1` , but I was unable to receive CSI data. Am I missing any steps?
> > Should I use PC1 to connect Tx and PC2 to connect Rx for capture CSI？
> > ![333](https://private-user-images.githubusercontent.com/52898164/288316505-eea5f931-f72b-40dc-9a39-209e4a85c90c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDE5MTQ2MDUsIm5iZiI6MTcwMTkxNDMwNSwicGF0aCI6Ii81Mjg5ODE2NC8yODgzMTY1MDUtZWVhNWY5MzEtZjcyYi00MGRjLTlhMzktMjA5ZTRhODVjOTBjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMDclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjA3VDAxNTgyNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTdiOTQzYzY5YWE0NWExZTQ2NTFiYjIzNzRjODYyMmZjMmQ4ODk5Nzg2MGQ1MzFkMDMzMTg3YjJhMTYyNjE0ZDImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.8PZ9BigN_7rbFCmT37Mnb50HuD9VaUdhkuBjc1zDg_o)
> 
> If you use `nexmon_tx_task` there is no need to `ping`.
> 
> Also I advise against using `ping` as a traffic generator in general. If you do not want to inject frames with `nexmon_tx_task` but generate traffic on tcpip level I suggest using `iperf`.
> 
> Not capturing any CSI UDPs can have many reasons, usually this is due to misconfiguration. Also check out the FAQ.

Thank you very much for your help！
I found that I was able to successfully collect CSI, I just had to wait for a while. The collection of two routers is not like the router and nexus5, which can display got0，got10，got20...
