### ISSUE TITLE
Nexus6P displays only the single antenna dimension after data acquisition and processing

### ISSUE THREAD

**Issue by doge0823** [seemoo-lab/nexmon_csi#333]
Hello, fellow developers. I encountered a problem. I learned that Nexus6P is a smart phone with dual antennas, so I used a Nexus6P phone installed with Nexmon firmware to collect data in the 5GHz band, 149 channel and 20MHz bandwidth. After processing by the MATLAB code shared by Github, only the data of single antenna dimension was displayed. I don't know whether it is because I lack any key commands during the experiment that I failed to collect the dual antenna data, or whether the MATLAB code provided needs to be modified before the dual antenna data can be extracted.

**Comment by jlinktu** [comment]
The matlab script provided here is only an example and simply displays CSI for all packets contained in the capture one-by-one. That means if you collected for both antennas CSI will be displayed alternating between the two antennas. You are free to re-use and extend the code and parts of it to sort the CSI by antenna before displaying them.
Alternatively, there are several projects that can process CSI captured from Nexus 6P using `nexmon_csi` and probably are capable of what you are looking for, e.g. [CSIKit](https://github.com/Gi-z/CSIKit), [csiread](https://github.com/citysu/csiread), and [nexcsi](https://github.com/nexmonster/nexcsi).
