### ISSUE TITLE
Router as Tx, RT-AC86U router as

### ISSUE THREAD

**Issue by sarielkk** [seemoo-lab/nexmon_csi#334]
Hello! Your work has been of great help to us.
 I would like to ask if nexmon is not suitable for ordinary routers as Tx and RT-AC86U as Rx? There is no nexmon folder in the project of bcm4366c0.
Whether the transmitter must be in frame injection mode（nexmon_tx_task） when collecting CSI through RT-AC86U.

**Comment by jlinktu** [comment]
You can use any type of wifi transmitter, up to ieee 802.11ac.
`nexmon_csi` doesn't know if a frame was injected or is legitimate traffic.

The advantage of using frame injection over ordinary traffic, e.g. with `nexmon_tx_task`, is that it gives you more control over the used bandwidth, encoding, rate, and amount of frames. This is usually desirable for controlled experiments, as those parameters are not controllable by the receiving end (or `nexmon_csi` extractor).

If you want to use an Asus RT-AC86U or any other AP to create legitimate traffic there is no need to use `nexmon` at all. I don't get what your question here is.
