### ISSUE TITLE
Confused about Tx and Rx

### ISSUE THREAD

**Issue by sarielkk** [seemoo-lab/nexmon_csi#335]
First of all, thank you very much for developing such a project, which has provided a lot of help for me to study CSI.
Secondly, after collecting data, I have some questions, hoping to get answers.
I use the TP-Link router as the launch end and the Nexus6P mobile phone (A) as the receiving end.

1. In monitor mode, Nexus 6P(also called A) monitoring specific channel data, so will the CSI collected by Nexus in different locations be different?
2. Does the router in the experiment only need to connect the power supply? I found that no matter whether the router was connected to the Internet, Nexus 6P could collect data, but collecting rates were different. Why can I collect data when not connect to the Internet? As far as I know, the router can only generate signals by only receiving power.
3. I don’t understand the definition of Rx in this scene. If we use another mobile phone(also called B) to connect the Internet of the router to generate data traffic, is Rx in this scene A or B?
5. When I use Nexus 6P to collect data, amplitude value is about 100 million levels. However, when I use Nexus 5 to collect data, amplitude value is about a thousand levels. Why is there such a large gap?

Looking forward to getting a reply, thanks again！
[Uploading c1n1.pcap.gz…]()

**Comment by jlinktu** [comment]
1. CSI is likely to differ in different locations. CSI can even differ in the exact same location as it is influenced by numerous conditions independent of location.
2. How you build your setup is up to you, including the way you generate traffic and how you configure a nexmon CSI extractor device. CSI is based on WLAN (Wireless **Local** Area Network) frames. The CSI extractor doesn't care if the WLAN frames' payload is data related to "Internet" content or just random stuff. It will extract CSI for each WLAN frame received by its radio that matches the parameters given by `makecsiparams`.
3. "_Rx_" is just shorthand for "_Receiver_". A receiver is typically the destination device of traffic. Thus, in your case B. However, it depends on how you see it.. as the monitor or CSI extractor device A also receives frames. If you want to differentiate more clearly you could call B "legitimate receiver" and call A "monitoring receiver".
4. The data formats of CSI extracted on `bcm4358` (Nexus 6P) and `bcm4339` (Nexus 5) have different formats with different resolutions. Check out the [README](https://github.com/seemoo-lab/nexmon_csi?tab=readme-ov-file#analyzing-the-csi) and our [Free Your CSI paper](https://github.com/seemoo-lab/nexmon_csi?tab=readme-ov-file#references) for more details on the data formats.
