### ISSUE TITLE
Some issues about transmission and received power 

### ISSUE THREAD

**Issue by pygj1994** [seemoo-lab/nexmon_csi#340]
Hello @jlinktu, under your guidance, I have obtained frames using the Jammer APP installed on Nexus 5 and ASUS router, as shown in the pictures.
（1）When there are many obstructions between Nexus 5 and ASUS router.
![9ababf70cecd5350c4705afe37a3974](https://github.com/seemoo-lab/nexmon_csi/assets/59013533/a13040a1-93e7-426f-a688-7f4424219003)

（2）When there are no obstructions between Nexus 5 and ASUS router.
![b171106efe38f11641f68ee923ee41a](https://github.com/seemoo-lab/nexmon_csi/assets/59013533/89e47d23-3e38-47ce-a1fd-abd12692e3c3)

Now, I have a few questions: (1) What is the transmission power when the transmitter power button in the Jammer APP is adjusted to the maximum of 100%? (2) What is the unit of magnitude in the figure? Usually the units of power are mW or dBm. But the values are so large in the first figure.

**Comment by jlinktu** [comment]
1) As far as I can tell by looking at the code, the power settings for the transmitter from within the app are never set inside the firmware. Thus, the transmission power is not affected by this setting. Alternatively, you should be able to set the transmission power with `nexutil -s505 -l1 -v<power index>`, where `<power index>` can be an integer value between `0` and `127` that translate to a transmission power, or `-1` to go back to default settings (chip controls it-self). However, I can't tell right now how the index translates to a power-related unit, you'll have to experiment there to get what suits you.
2) Well.. you created the figure, thus, you should know best what you are showing there. If you wanted to ask for a unit of the CSI's magnitude, there is none. CSI resembles an estimate of change in amplitude and phase. The magnitude of this estimate doesn't have a unit.

_Hint: You wan't to filter out the values for guard carriers and the null carrier, as they disturb your plot. This was discussed several times on issues here and is also mentioned in the [FAQ section of the README](https://github.com/seemoo-lab/nexmon_csi?tab=readme-ov-file#frequently-asked-questions)._
