### ISSUE TITLE
The nexutil doesn't work 

### ISSUE THREAD

**Issue by Asafe33** [seemoo-lab/nexmon_csi#347]
Hey everybody. I've been working with Wi-Fi CSI for a few months, but I'm having trouble capturing CSI data. I followed the steps provided by @zeroby0 and installed from https://github.com/nexmonster/nexmon_csi_bin/.

However, at this point, I encountered a difficulty (see the picture). Nexutil is installed, but it's showing this error.

I'm using VirtualBox on my laptop to emulate Ubuntu, and wlan0 has changed to enp0s3 (TCPDUMP).

This error seems similar to one I encountered on 2021-01-11-raspios-buster-armhf-full (see picture 2). In both cases, I've installed Nexmon (disassembling ucode shows).

![1](https://github.com/seemoo-lab/nexmon_csi/assets/170462513/e46bf517-b60b-4e13-a7fa-4cdded62bd72)
![2](https://github.com/seemoo-lab/nexmon_csi/assets/170462513/c06ddcf0-6d6f-4371-a51e-537c08926514)
![3](https://github.com/seemoo-lab/nexmon_csi/assets/170462513/5c177980-f07e-4edf-994e-0726424202ee)
![4](https://github.com/seemoo-lab/nexmon_csi/assets/170462513/0bc707fd-19c2-4d72-b7c8-cb0be432f151)

The pictures below are from Kernel 5.4.83-v8+. The backgrounds you see are from this kernel (2,3,4), but the other one is from Kernel 5.10.92 (1).

If anyone has a solution, I'd really appreciate it. 

@jlinktu @zeroby0

**Comment by Asafe33** [comment]
I didn't find any solutions in the previous ones.

**Comment by zeroby0** [comment]
Maybe you're substituting lowercase letter L for 1 in -l34. Copy paste instead of typing.

**Comment by Asafe33** [comment]
Thank you, now it works!
