### ISSUE TITLE
IP Address Issues After Installing Nexmon CSI Patch: DNS_Probe_Finished_No_internet

### ISSUE THREAD

**Issue by kuku000** [seemoo-lab/nexmon_csi#362]
Description:

After installing the Nexmon CSI patch, I am experiencing issues with my device's IP address. The IP address keeps changing, which prevents me from connecting to the internet.

Details:

Device Model: Raspberry pi 3B+
Operating System: 5.4.83

**Comment by jlinktu** [comment]
Do you mean a local IP address of the wireless interface? If yes, you are not supposed to connect to an AP with the Nexmon CSI patched firmware running, thus no external DHCP on your wireless interace.

**Comment by kuku000** [comment]
Thx
