### ISSUE TITLE
sequence number problem

### ISSUE THREAD

**Issue by kuku000** [seemoo-lab/nexmon_csi#365]
Hello,

I am currently using Raspberry Pi 3B+ to extract CSI data from a wireless card and transmitting it via UDP to a client for analysis. During this process, I have noticed that some packets have repeating seq no values. I would like to understand if this is related to packet retransmissions, and whether it could affect the accuracy of CSI data or the final analysis results.

Specifically, when there are consecutive packets with the same seq no, could this lead to inaccuracies or misinterpretation of the data? Would repeated seq no impact applications like CSI-based fingerprinting or other similar uses?

I greatly appreciate your assistance!

Thank you!!! 

![image](https://github.com/user-attachments/assets/4343da01-7aab-4d08-8ff0-c17aac67ac11)

**Comment by jlinktu** [comment]
If you are talking about the sequence number fetched from the IEEE 802.11 MAC header, then no, this should not affect any CSI interpretation. A retransmission on IEEE 802.11 MAC layer requires a full retransmission on the PHY layer, which means, besides carrying the same payload, is more or less independent of the former transmission.

**Comment by kuku000** [comment]
Thx !!!
