### ISSUE TITLE
How to read csi on Raspberry Pi B4?

### ISSUE THREAD

**Issue by coldcoldmilk** [seemoo-lab/nexmon_csi#37]
Hi,i have captured the DUP packets,is there a program to reading csi from a Raspberry Pi B4？What if not?

**Comment by Junye97** [comment]
Hi there,

There is a Matlab script provided: ./src/matlab/csiread.m

Otherwise you can use apps like wireshark to inspect the raw pcap output. 

 Cheers

**Comment by coldcoldmilk** [comment]
Thank you for your help.
However, I would like to be able to do everything in the Raspberry Pi, including reading csi information.But,i can't install matlab on the Raspberry Pi.
I'm very upset.
I'm trying to read ./src/matlab/csiread.m, and try to rewrite it in python.

**Comment by coldcoldmilk** [comment]
> Hi there,
> 
> There is a Matlab script provided: ./src/matlab/csiread.m
> 
> Otherwise you can use apps like wireshark to inspect the raw pcap output.
> 
> Cheers

Thank you for your help.
However, I would like to be able to do everything in the Raspberry Pi, including reading csi information.But,i can't install matlab on the Raspberry Pi.
I'm very upset.
I'm trying to read ./src/matlab/csiread.m, and try to rewrite it in python.

**Comment by Junye97** [comment]
MATLAB is a very demanding program... If you are looking for realtime CSI decoding that might be a lot to ask for a Pi, the next best thing in my opinion is to open the port 5500 and have a remote device that does it.

**Comment by mzakharo** [comment]
Rpi is perfectly capable for realtime CSI decoding, if you keep your sounding rate low, like 10-100HZ. Just make sure you use the compiled C decoder.

**Comment by coldcoldmilk** [comment]
> MATLAB is a very demanding program... If you are looking for realtime CSI decoding that might be a lot to ask for a Pi, the next best thing in my opinion is to open the port 5500 and have a remote device that does it.

Thank you very much for your answer.

**Comment by coldcoldmilk** [comment]
> MATLAB is a very demanding program... If you are looking for realtime CSI decoding that might be a lot to ask for a Pi, the next best thing in my opinion is to open the port 5500 and have a remote device that does it.

Thank you very much for your answer.

**Comment by zeroby0** [comment]
Also, people seem to be facing issues with Pi 4. #41 #39
I'm using a pi 3B+ and everything seems to be going good, but I've not collected 40K packets like these people did. If you do get into problems, check using a 3B+ too.

**Comment by mzakharo** [comment]
This is not a 3+ vs 4 issue. Crash occurs if you get amsdu and duplicate frames. Not everyone operates in wifi environments that capture those.
