### ISSUE TITLE
Installation Issue on Raspberry Pi4

### ISSUE THREAD

**Issue by Jaesuru** [seemoo-lab/nexmon_csi#370]
Hi, I currently am trying to install Nexmon patch onto my Raspberry Pi4b. It’s also running kernel version 5.10.63-v7l+. However, when I am at the step to do “make install-firmware”, I run into an issue and it says:

make[1]: *** /lib/modules/5.10.63-v7l+/build: No such file or directory. Stop.
make: *** [Makefile:50: brcmfmac.ko] Error 2

Any help appreciated, huge newbie on this and have been stuck on it for the longest time.

thank you.

**Comment by jlinktu** [comment]
Search issues for "build: No such file or directory".
