### ISSUE TITLE
Extract RSSI and CSI from `.pcap` file

### ISSUE THREAD

**Issue by YiwenWang-YOLO** [seemoo-lab/nexmon_csi#372]
@mzakharo  I would like to ask for your help. I used this repo to get the `.pcap` file using ASUS RT AC86U. But I don't know how to get RSSI from it. I want to extract the RSSI from `csireader.m` in `f.payload`.  But I don't know if RSSI is encoded in this and if it is how can I get it , am I using a MIMO system (4x4) should I be reading 4 RSSI(corresponding to the four receiving antennas) . If there is no RSSI in the payload, where can I get the RSSI from？

**Comment by jlinktu** [comment]
https://github.com/seemoo-lab/nexmon_csi/issues/126#issuecomment-704981416
