### ISSUE TITLE
Asus router installation timeout

### ISSUE THREAD

**Issue by bachejames** [seemoo-lab/nexmon_csi#56]
Hi there,

Thanks so much for putting this together - really cool!

I am however stuck when trying to install on the Asus Router. During execution of step 7 (`make install-firmware REMOTEADDR=<address of your rt-ac86u>`), I get the following:

This line runs for about 130 seconds: `COPYING TO ROUTER dhd.ko -> /jffs/dhd.ko` before I then get this:
`ssh: connect to host <address of your rt-ac86u> port 22: Connection timed out`
`lost connection`

Any ideas why please? It is perhaps a router setting I can change to increase time before timeout?

Thanks so much :)

**Comment by jlinktu** [comment]
Did you substitute _\<address of your rt-ac86u\>_ with the IP address of your router?
If not, you are supposed to do so.

**Comment by bachejames** [comment]
Resolved - had to turn ssh on
