### ISSUE TITLE
External antenna, estimated AOA

### ISSUE THREAD

**Issue by 289536718** [seemoo-lab/nexmon_csi#60]
Hello.
I'm trying to use Raspberry 4B to estimate AOA from CSI, but it needs an external antenna. So how do I do it? Can you give me some advice?

Thank you very much.

**Comment by jlinktu** [comment]
One issue on this on either [nexmon_csi](https://github.com/seemoo-lab/nexmon_csi) or [nexmon](https://github.com/seemoo-lab/nexmon) should be enough.
https://github.com/seemoo-lab/nexmon/issues/394

**Comment by 289536718** [comment]
I have seen the reply from Mr. Matthias. Thank you and Matthias very much.




------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"Jakob Link"<notifications@github.com&gt;;
发送时间:&nbsp;2020年4月16日(星期四) 凌晨1:50
收件人:&nbsp;"seemoo-lab/nexmon_csi"<nexmon_csi@noreply.github.com&gt;;
抄送:&nbsp;"Blackcofe"<289536718@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [seemoo-lab/nexmon_csi] External antenna, estimated AOA (#60)





 
One issue on this on either nexmon_csi or nexmon should be enough.
 seemoo-lab/nexmon#394
