### ISSUE TITLE
How are the CSI packets timestamped?

### ISSUE THREAD

**Issue by Junye97** [seemoo-lab/nexmon_csi#63]
Hi there,

To my understanding, each captured CSI frame contains its own epoch timestamp. My question is, is each timestamp fetched directly from the system (e.g. from Linux), or only one timestamp is fetched while the rest are calculated? How does this play out when I update the system time during CSI collection? I’m running Nexmon CSI on a Raspberry Pi 4B. Thank you very much.

Cheers

**Comment by mzakharo** [comment]
I believe the timestamps are part of https://github.com/torvalds/linux/blob/master/Documentation/networking/timestamping.txt

Namely, ```SOF_TIMESTAMPING_RX_SOFTWARE```

**Comment by Junye97** [comment]
Thank you for your reply. So this basically means the timestamps are generated Individually by requesting the timestamp from the OS? But I couldn’t find any code in Nexmon repo with 

``
SOF_TIMESTAMPING_RX_SOFTWARE
``

**Comment by mzakharo** [comment]
Thats because the source code for SOF_TIMESTAMPING is entirely inside Linux kernel source. all nexmon does is generate a UDP packet, and pass it over to linux networking stack. rest you can follow from linux sources.

**Comment by Junye97** [comment]
Thank you for your help. I'm closing the issue.
