### ISSUE TITLE
D11 or radio PHY register list 

### ISSUE THREAD

**Issue by MauriceSaccani** [seemoo-lab/nexmon_csi#68]
Hi, do exists a list of register addresses/content of the D11 core or the radio core (similar to those included onto patch files but with more low level registers?)

> #define		ClassifierCtrl		0x140
> #define		core0_crsControlu	0x167D
> #define		core0_crsControll	0x167C
> #define		core0_crsControluSub1	0x167F
> #define		core0_crsControllSub1	0x167E
> #define		core0_computeGainInfo	0x6D4
> #define		ed_crsEn		0x339
> #define		BBConfig		0x1
> #define		RfseqMode		0x400

**Comment by jlinktu** [comment]
Hi,
have a look at this header file:
https://github.com/MerlinRdev/86u-merlin/blob/master/release/src-rt-5.02hnd/bcmdrivers/broadcom/net/wl/impl51/4365/src/wl/phy/wlc_phyreg_ac.h
