### ISSUE TITLE
set up a server on one router and an client on another router ASUS RT-AC86U

### ISSUE THREAD

**Issue by yujianyuanhaha** [seemoo-lab/nexmon_csi#85]
greetings,

i have successfully collect CSI in **monitor mode** (by `/usr/sbin/wl -i eth6 monitor 1`) on ASUS RT-AC86U router, however I notice only part of the CSI in earlier UDP packet have value, most of the CSI in following packet are all zeros. which i guess it come from the monitor mode and communication would not last long.

I am now trying to set up a server on one router and an client on another router ASUS RT-AC86U, so that they maintain a stable wireless communication. I get to know the set the server by run `iperf3 -s -D` on one router, while I have no idea how to set a client, and how to make sure the CSI it get come from the server-client link? Is there any clue I can refer to? @matthiasseemoo @@jlinktu

Some method I have tried but not work:

1. The [issue 16](https://github.com/seemoo-lab/nexmon_csi/issues/16#issuecomment-554116692) mention there is a program written in C, but it is not available for bcm4660c0. 

2. monitor with specific mac address, e,g. let router 2 monitor the router  1 packet, with the encode string `./makecsiparams -c 157/40 -C 1 -N 1 -m MacAddrA: MacAddrB`, where MacAddrA is eth5/2.4GHz mac address, MacAddrB is eth6/5GHz mac address. Then tcpdump by `./tcpdump -i eth6 dst port 5500 -w savedfile.pcap`.
However, there is zero package captured in this way at 5GHz, it work for 2.4GHz with channel setting 11/20 (channel No.11 20MHz).
**Update** I later figure out I should go with `./makecsiparams -c 157/80 -C 0x0f -N 0x0f -m MacAddrA: MacAddrB`, then I got the package, and monitor mode is good enough to get the CSI.

3. use `wl join ssid keys` command to let router 2 join in  the router  1, while show error `wl: unsuported`, looks like only part of the function is supported in AC86U.

Best.

**Comment by Qingfengxulailu** [comment]
have solved？
