### ISSUE TITLE
CSI definition at monitor mode 

### ISSUE THREAD

**Issue by yujianyuanhaha** [seemoo-lab/nexmon_csi#92]
In monitor mode, does the CSI present the wireless link between the sniffer and the transmitter, or the wireless link between the transmitter and corresponding receiver?

e.g. In the figure below, **router A** is communication with **device B**, while **sniffer router X**  is collect CSI in monitor mode. Does the CSI describe the **wireless link AB**, or the **wireless link AX**?
![sniffer (1)](https://user-images.githubusercontent.com/9403813/84724819-10f92380-af57-11ea-8325-e6720d555735.jpg).

@matthiasseemoo @jlinktu @zeroby0  @289536718 I am aware it is a fundamental problem I suspect it is **link AB** but I am not pretty sure...

**Comment by zeroby0** [comment]
Link AX. CSI is measured using a known training sequence in WiFi frames. X compares the sequence it recieves to the how it should be, and determines CSI. CSI is just impulse response in a way.

**Comment by yujianyuanhaha** [comment]
Got it, thanks bro~ @zeroby0
